
import re
def autocorrect(sentence):
    # Mapping of incorrect phrases to their corrections
    corrections = {
        "party": "part A",
        "part A or be": "part a and part b",
        "part be": "part b",
        "hobby": "part b",
        "part mb": "part a and part b",
        "part amy": "part a and b",
        "party or b": "part a",
        "parte": "part b",
        "party bee": "medicare part a and b",
        "medicare part amb": "part b",
        "park he": "medicare part a and b",
        "medicare part hamby": "part a and b",
        "part md": "part b",
        "part beep": "part a and part b",
        "part a mb": "part b",
        "part aop": "part a and part b",
        "part a or point b": "part b",
        "medicare part i imb": "part a and part b",
        "parte": "part a and part b",
        "medicare part namby": "part a and part b",
        "medicare part avenue": "part a and part b",
        "part a mp": "part a and part b",
        "part a and partly": "part b",
        "part fee": "part a and part b",
        "part a and barbie":"part a and part b",
         "medicare part andy beef":"part a and part b",
        "parted":"part a ",
        " i have medicare part effigy" : "i have medicare part a and b",
        "yeah party empathy":"yeah part a and b",
        "part key":" i've got part b",
        "i have bought":"i have both",
        "part three":"part b",
        "part eight":"part b",
        "amy":"a and b",
        "mb":"b",
        " part a m b":"part a and b",
        "party": "part A",
        "humana part day": "have part a",
        "medicare part eight mb": "medicare part a and b",
        "part md": "part b",
        "aria medicare": "a medicare",
        "medicare gas": "maedicare a",
        "medicare tbd": "maedicare b",
        "partake": "part a",
        "only party": "only part a",
        "part andy": "part a and b",
        "part i and me": "part a and b",
        "part a and body": "part a and b",
        "not a party game see": "not a part a have c",
        "part a honeybee": "part a and b",
        "parte envy": "part a and b",
        "no lonely parties": "no lonely part b",
        "party or big": "part a or b",
        "partial": "part a",
        "part three": "part c",
        "part effigy": "part a b",
        "party empathy": "part a and b",
        "part she": "part c",
        "part a m b": "part a and b",
        "medicare pay": "medicare part a",
        "medicare again be": "medicare a and b",
        "the party fabric": "the part a and b",
        "part a and barbie": "part a and b",
        "medicare part andy beef": "medicare a and b",
        "parted": "part a",
        "part lnb": "part a and b",
        "part may": "part a",
        "part key": "i've got part b",
        "part vi": "part b",
        "part age": "part a",
        "part a and being": "part a and b",
        "part A or be": "part a or part b",
        "part be": "part be",
        "hobby": "part b",
        "part mb": "part b",
        "part amy": "part a or part b",
        "party or b": "part a or b",
        "party bee": "part b",
        "park he": "part b",
        "medicare part hamby": "medicare part a and b",
        "part md": "part a or b",
        "part beep": "part b",
        "part aop": "part b",
        "part a or point b": "part a or part b",
        "medicare part i imb": "part a or part b",
        "parte": "part b",
        "medicare part namby": "part a or part b",
        "medicare part avenue": "part a or part b",
        "part a mp": "part a or part b",
        "part a and partly": "part a or part b",
        "part fee": "part b",
        "got part beat": "have part b",
        "part a base": "part a and b",
        "part eh": "part a",
        "part zombie": "part b",
        "bart bi": "part b",
        "part egg": "part a",
        "knobby": "not b",
        "part ambi": "part a and b",
        "a n b": "part a and part b",
        "part ape": "part a",
        "just partly": "just part b",
        "part a a be": "part a and b",
        "parts i envy": "part a and b",
        "party and b": "part a and b",
        "party b cnd": "part b c and d",
        "part me": "part be",
        "part beach": "part b",
        "part a amy": "part a and b",
        "part a mb": "part a and b",
        "part eight": "part a",
        "party or party": "part a or b",
        "part a n blue": "part a and part b",
        "party party": "part a or part b",
        "i am to the half": "i dont have",
        "i heard party": "i have part a",
        "i have but we": "i have part b",
        "part a in fact be": "part a and part b",
        "i then now": "i don't know",
        "i have bought": "i have both",
        "rowboat": "robot",
        "i have five see": "i have part c",
        "part he" :"part b",
        " part a and bates":"part a and b",
        " beta":"b",
        "part an e": "part a and b",
        "party fade": "part a",
        "part blur": "part b",
        "part age": "part a",
        "medicare beam": "medicare part b",
        "medicare perk": "medicare part",
        "party tale": "part a",
        "have aca" :"good",
        "part bay": "part b",
        "a nb":"part a and b",
        "part aob":"part a or b",
        "part imho"	:"part b",
        "part alien b":	"part a and b",
        "party and ble":	"part a and b",
        "part i e bay":	"part a and b",
        "part act":"part a",
        "party bag":	"part b",
        "part gate":	"part a",
        "just party":"just part a",
        "medicare part a and the": "medicare part a and b",
        "body a and c": "part a and b",
        "party and be":"part a and b",
        "party and barbie ": "part a and part b",
        "medicare for a n party" :"medicare part a or b",
        "part a b c d e and f": "medicare part a and b",
        "part eighty":"part a and b",
        "part fa":"part a",
        "part a and gif":"part a and b",
        "part to be":"part b",
        "part mb":"part a and b",
        "part d m v bitch":"part a and b",
        "part fate":"part a",
        "part day":"part a",
        "partly due":"part b",
        "part a beast":"part a and b",
        "partying or port b":"part a or part b",
        "part of me":"part a and b",
        "party and be empty":"part a and b",
        "part deep":"part b",
        "parsi":"part c",
        "part bit":"part b",
        "good by":"good bye",
        "year":"yeah", 
        "blue and or right":"red blue and white card",
        "as i be":"i got b",
        "at that be":"i got b",
        "have a be": "i have a b",
        
    }
    
    # Create a single regular expression pattern from the corrections dictionary
    pattern = re.compile('|'.join(re.escape(incorrect) for incorrect in corrections.keys()))
    
    # Define a replacement function that uses the dictionary to get the correct replacement
    def replacement(match):
        return corrections[match.group(0)]
    
    # Use re.sub to replace all occurrences in the sentence
    corrected_sentence = pattern.sub(replacement, sentence)
    
    return corrected_sentence
    # for incorrect, correct in corrections.items():
    


